### Boosting
* 간단하면서도 성능이 매우 높은 앙상블 기법
* 학습 round를 진행하며 모델을 생성 -> 모델에 의해 오답 weight를 업데이트
* instance weight가 높은 instance를 중심으로 모델을 생성
* 해당 모델들로 앙상블 모델을 만듬
* error를 가지고 데이터를 분류
* 깊지 않은 디시전트리를 사용

* Adaboost : max_depth를 작게

In [1]:
import numpy as np

In [2]:
elements = ['one', 'two', 'three'] 
weights = [0.2, 0.3, 0.5]

from numpy.random import choice
print(choice(elements, size=10, replace=True, p=weights))

['two' 'one' 'three' 'three' 'three' 'three' 'one' 'three' 'three' 'three']


In [3]:
X = np.load("./tatanic_X_train.npy")
y = np.load("./tatanic_y_train.npy")

In [4]:
X[0]

array([0.27345609, 0.01415106, 0.        , 1.        , 0.        ,
       0.125     , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [5]:
y[:10]

array([0., 1., 1., 1., 0., 0., 0., 0., 1., 1.])

In [6]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier


In [7]:
eclf = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=2), n_estimators=500, 
                          learning_rate=0.1)

In [8]:
from sklearn.model_selection import cross_val_score
cross_val_score(eclf, X, y, cv=5).mean()

0.8177743921792675

In [9]:
from sklearn.tree import DecisionTreeClassifier
DecisionTreeClassifier()

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [10]:
AdaBoostClassifier()

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [11]:
params = {"base_estimator__criterion" : ["gini", "entropy"],
          "base_estimator__max_features" : [7,8,],
          "base_estimator__max_depth" : [1,2],
          "n_estimators": [23,24, 25, 26, 27],
          "learning_rate": [0.4, 0.45, 0.5, 0.55, 0.6]
         }

In [12]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=eclf, param_grid=params, cv=5, n_jobs=7)
grid = grid.fit(X, y)

In [13]:
grid.best_score_

0.8335208098987626

In [14]:
grid.best_params_

{'base_estimator__criterion': 'entropy',
 'base_estimator__max_depth': 2,
 'base_estimator__max_features': 7,
 'learning_rate': 0.55,
 'n_estimators': 25}

In [15]:
grid.best_estimator_.feature_importances_

array([0.22502182, 0.18537001, 0.04250254, 0.07161709, 0.03918056,
       0.08655522, 0.06159805, 0.02792639, 0.0068253 , 0.01756819,
       0.01824419, 0.        , 0.01439093, 0.00955463, 0.02395896,
       0.04185276, 0.03267525, 0.02605733, 0.00412884, 0.        ,
       0.        , 0.02071991, 0.0095789 , 0.00981752, 0.        ,
       0.01554317, 0.00931246])