### 파이썬 및 넘파이 변형

tf.constant()를 이용하면 파이썬 리스트나 넘파이 배열을 상수 텐서로 만들 수 있다.

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

In [3]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [4]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

### 일차원 수열 텐서

일차원 수열 텐서를 마들 때는 range 또는 linsapce 등의 메서드를 사용할 수 있다. linspace를 사용할 때는 start 값이 부동소수점이어야 한다.

In [5]:
tf.range(5)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [6]:
tf.linspace(0.0,5,11)

<tf.Tensor: shape=(11,), dtype=float32, numpy=
array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ],
      dtype=float32)>

### 0 or 1 로 구성된 텐서

이 밖에도 상수 텐서를 생성하는 다양한 메서드들이 제공된다. 대부분의 메서드는 배열의 크기를 지정하는 shape 또는 데이터 자료형을 지정하는 dtype 인수를 받는데 shape 인수는 (행 갯수, 열 갯수) 형태의 튜플이나 리스트로 전달해야 한다. dtype 인수는 지정하지 않을 경우 tf.float32 자료형 즉 32비트 부동소수점 자료형을 사용한다.

In [8]:
tf.zeros((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [9]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [10]:
tf.fill([2,3],2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 2, 2],
       [2, 2, 2]], dtype=int32)>

In [11]:
tf.zeros_like([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [12]:
tf.ones_like([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

### 난수 텐서

무작위 난수값을 가지는 상수 텐서 자료형 생성메서드는 random 서브패키지에서 제공한다.

In [14]:
tf.random.set_seed(0)

In [15]:
tf.random.uniform((2,3),seed=0)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.01975703, 0.00704217, 0.18987215],
       [0.7772658 , 0.41817415, 0.7437942 ]], dtype=float32)>

In [ ]:
# 절단정규분포(평균을 기준으로 표준편차보다 크거나 작은 데이터를 제외)

In [16]:
tf.random.truncated_normal((2,3),seed= 0)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.12391895, -1.7961729 ,  0.31075957],
       [-1.3194942 ,  0.5543462 , -0.9617468 ]], dtype=float32)>

In [17]:
tf.random.shuffle([1,2,3,4,5,6])

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([4, 6, 2, 3, 1, 5], dtype=int32)>

### 텐서의 속성

In [18]:
a = tf.range(6, dtype=tf.int32)

In [19]:
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5], dtype=int32)>

In [20]:
a.ndim

1

In [21]:
a.shape

TensorShape([6])

In [22]:
a.dtype

tf.int32

In [23]:
a.numpy()

array([0, 1, 2, 3, 4, 5], dtype=int32)

### 크기와 차원 변환

다음은 텐서의 크기 및 차원을 바꾸는 명령이다.

In [24]:
a_2d = tf.reshape(a,(2,3))
a_2d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]], dtype=int32)>

In [25]:
a_2d_t = tf.transpose(a_2d)  # 2x3 크기의 2차원 행렬을 3x2 크기의 2차원 행렬로 변환
a_2d_t

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 3],
       [1, 4],
       [2, 5]], dtype=int32)>

In [26]:
a_3d = tf.expand_dims(a_2d,0) #  2x3 크기의 2차원 행렬을 1x2x3 크기의 3차원 행렬로 변환
a_3d

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[0, 1, 2],
        [3, 4, 5]]], dtype=int32)>

In [27]:
a_4d = tf.expand_dims(a_3d,3) # 1x2x3 크기의 3차원 행렬을 1x2x3x1 크기의 4차원 행렬로 변환
a_4d

<tf.Tensor: shape=(1, 2, 3, 1), dtype=int32, numpy=
array([[[[0],
         [1],
         [2]],

        [[3],
         [4],
         [5]]]], dtype=int32)>

In [28]:
a_1d = tf.squeeze(a_4d) #1x2x3x1의 4차원 행렬을 1차원 벡터로 변환
a_1d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]], dtype=int32)>

### 분할과 합체

벡터/행렬을 나누거나 두 개 이상의 벡터/행렬을 합치는 명령어도 많이 사용된다.

In [29]:
a0 = tf.reshape(tf.range(12), (3, 4))
a0

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [30]:
tf.slice(a0, [0,1] ,[2,3]) # (0, 1)위치에서 (2개, 3개)만큼 뽑아낸다.

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]], dtype=int32)>

In [31]:
a1 , a2 = tf.split(a0, num_or_size_splits=2, axis=1) # 가로축(axis=1)을 따라 2개로 분할
print(a1)
print(a2)

tf.Tensor(
[[0 1]
 [4 5]
 [8 9]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  3]
 [ 6  7]
 [10 11]], shape=(3, 2), dtype=int32)


In [32]:
tf.concat([a1,a2],1) # 가로축(axis=1)을 따라 a1, a2를 합치기

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [33]:
tf.tile(a1,[1,3]) # 가로축(axis=1)을 따라 3개로 복사-붙이기

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 0, 1, 0, 1],
       [4, 5, 4, 5, 4, 5],
       [8, 9, 8, 9, 8, 9]], dtype=int32)>

In [34]:
a3 = tf.stack([a1, a2]) # 3x2 행렬 a1, a2를 추가적인 차원으로 붙여서 2x3x2 고차원 텐서 생성
a3

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]], dtype=int32)>

In [35]:
tf.unstack(a3, axis=1)  # 2x3x2 고차원 텐서를 0차원으로 풀어서 3개의 2x2 행렬 생성

[<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[4, 5],
        [6, 7]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 8,  9],
        [10, 11]], dtype=int32)>]