## Confusion Matrix

In [2]:
from sklearn.metrics import confusion_matrix
y_true = [1, 0, 1, 1, 0, 1]
y_pred = [0, 0, 1, 1, 0, 1]
confusion_matrix(y_true, y_pred)

array([[2, 0],
       [1, 3]], dtype=int64)

In [3]:
tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
(tn, fp, fn, tp)

(2, 0, 1, 3)

## Accuracy
* 전체 데이터 대비 정확하게 예측할 확률

In [4]:
import numpy as np
from sklearn.metrics import accuracy_score
y_pred = np.array([0, 1, 1, 0])
y_true = np.array([0, 1, 0, 0])

In [5]:
sum(y_true == y_pred) / len(y_true)

0.75

In [6]:
accuracy_score(y_true, y_pred)

0.75

In [7]:
accuracy_score(y_true, y_pred, normalize=False)

3

## Precision
* 1이라고 예측한 비율 중에 진짜 1일 확률

In [8]:
from sklearn.metrics import precision_score

In [9]:
y_pred = np.array([0, 1, 1, 0])
y_true = np.array([0, 1, 0, 0])

In [10]:
sum((y_pred == 1) & (y_pred == y_true)) / sum(y_pred)

0.5

In [11]:
precision_score(y_true, y_pred)  

0.5

In [12]:
y_true = [0, 1, 2, 0, 1, 2]
y_pred = [0, 2, 1, 0, 0, 1]
confusion_matrix(y_true, y_pred)

array([[2, 0, 0],
       [1, 0, 1],
       [0, 2, 0]], dtype=int64)

* macro : 각 라벨 값에 대하여 precision 후 평균

In [13]:
precision_score(y_true, y_pred, average='macro')  

0.2222222222222222

* micro : 전체 평균

In [14]:
precision_score(y_true, y_pred, average='micro')  

0.3333333333333333

* 각 라벨 값에 대하여 precision

In [15]:
precision_score(y_true, y_pred, average=None)  

array([0.66666667, 0.        , 0.        ])

## Recall
* 실제 1인 데이터중에 1이라고 예측한 비율

In [16]:
from sklearn.metrics import recall_score

In [17]:
y_pred = np.array([0, 1, 1, 0])
y_true = np.array([0, 1, 0, 0])

In [18]:
y_true = [0, 1, 2, 0, 1, 2]
y_pred = [0, 2, 1, 0, 0, 1]
recall_score(y_true, y_pred, average='macro')  

0.3333333333333333

In [19]:
recall_score(y_true, y_pred, average='micro')  

0.3333333333333333

In [20]:
recall_score(y_true, y_pred, average=None)

array([1., 0., 0.])

## F1
* precision과 recall의 종합지표

In [21]:
from sklearn.metrics import f1_score
y_pred = np.array([0, 1, 1, 0])
y_true = np.array([0, 1, 0, 0])

In [22]:
pre = precision_score(y_true, y_pred)  
rec = recall_score(y_true, y_pred)  

In [23]:
2 * (pre * rec) / (pre + rec)

0.6666666666666666

In [24]:
f1_score(y_true, y_pred)

0.6666666666666666

In [25]:
y_true = [0, 1, 2, 0, 1, 2]
y_pred = [0, 2, 1, 0, 0, 1]
f1_score(y_true, y_pred, average='macro')  

0.26666666666666666

In [26]:
f1_score(y_true, y_pred, average='micro')  

0.3333333333333333

In [27]:
f1_score(y_true, y_pred, average=None)

array([0.8, 0. , 0. ])

## Examples

In [28]:
import numpy as np
from sklearn.metrics import precision_recall_curve
y_true = np.array([0, 0, 1, 1])
y_scores = np.array([0.1, 0.4, 0.35, 0.8])
precision, recall, thresholds = precision_recall_curve(
    y_true, y_scores)

In [29]:
precision  

array([0.66666667, 0.5       , 1.        , 1.        ])

In [30]:
recall

array([1. , 0.5, 0.5, 0. ])

In [31]:
thresholds

array([0.35, 0.4 , 0.8 ])

In [32]:
from sklearn.metrics import precision_recall_curve
import matplotlib.pyplot as plt

plt.step(recall, precision, color='b', alpha=0.2,
         where='post')
plt.fill_between(recall, precision, step='post', alpha=0.2,
                 color='b')

plt.xlabel('Recall')
plt.ylabel('Precision')
plt.ylim([0.0, 1.05])
plt.xlim([0.0, 1.05])

(0.0, 1.05)

In [33]:
from sklearn.metrics import classification_report
y_true = [0, 1, 2, 2, 2]
y_pred = [0, 0, 2, 2, 1]
target_names = ['class 0', 'class 1', 'class 2']

In [34]:
print(classification_report(y_true, y_pred, target_names=target_names))

             precision    recall  f1-score   support

    class 0       0.50      1.00      0.67         1
    class 1       0.00      0.00      0.00         1
    class 2       1.00      0.67      0.80         3

avg / total       0.70      0.60      0.61         5

