In [3]:
from sklearn.externals import joblib

In [4]:
def get_nouns():
    pass

In [5]:
with open('data/hot-news.pkl','rb') as f:
    data =joblib.load(f)
locals().update(data)

In [6]:
import pandas as pd

In [7]:
article = pd.read_csv('data/폭염.csv', encoding='cp949',engine='python')

In [8]:
article

주소        일자     언론사  \
0      http://www.bigkinds.or.kr/news/newsDetailView....  20180101    부산일보   
1      http://www.bigkinds.or.kr/news/newsDetailView....  20180101    국민일보   
2      http://www.bigkinds.or.kr/news/newsDetailView....  20180101   아시아경제   
3      http://www.bigkinds.or.kr/news/newsDetailView....  20180101    한국경제   
4      http://www.bigkinds.or.kr/news/newsDetailView....  20180101    국제신문   
5      http://www.bigkinds.or.kr/news/newsDetailView....  20180101    중도일보   
6      http://www.bigkinds.or.kr/news/newsDetailView....  20180102    문화일보   
7      http://www.bigkinds.or.kr/news/newsDetailView....  20180102    경남신문   
8      http://www.bigkinds.or.kr/news/newsDetailView....  20180102   아시아경제   
9      http://www.bigkinds.or.kr/news/newsDetailView....  20180102    매일신문   
10     http://www.bigkinds.or.kr/news/newsDetailView....  20180102   아시아경제   
11     http://www.bigkinds.or.kr/news/newsDetailView....  20180103    경남신문   
12     http://www.bigkinds.or.kr/news/newsDetailView....  20180103    경인일보   
13     http://www.bigkinds.or.kr/news/newsDetailView....  20180103    중도일보   
14     http://www.bigkinds.or.kr/news/newsDetailView....  20180103    전남일보   
15     http://www.bigkinds.or.kr/news/newsDetailView....  20180103    제민일보   
16     http://www.bigkinds.or.kr/news/newsDetailView....  20180103    매일신문   
17     http://www.bigkinds.or.kr/news/newsDetailView....  20180103    국민일보   
18     http://www.bigkinds.or.kr/news/newsDetailView....  20180103  경남도민일보   
19     http://www.bigkinds.or.kr/news/newsDetailView....  20180104   아시아경제   
20     http://www.bigkinds.or.kr/news/newsDetailView....  20180104   아시아경제   
21     http://www.bigkinds.or.kr/news/newsDetailView....  20180104    경기일보   
22     http://www.bigkinds.or.kr/news/newsDetailView....  20180104    중부일보   
23     http://www.bigkinds.or.kr/news/newsDetailView....  20180104   머니투데이   
24     http://www.bigkinds.or.kr/news/newsDetailView....  20180104    부산일보   
25     http://www.bigkinds.or.kr/news/newsDetailView....  20180104    한국일보   
26     http://www.bigkinds.or.kr/news/newsDetailView....  20180104   머니투데이   
27     http://www.bigkinds.or.kr/news/newsDetailView....  20180104   헤럴드경제   
28     http://www.bigkinds.or.kr/news/newsDetailView....  20180104   아시아경제   
29     http://www.bigkinds.or.kr/news/newsDetailView....  20180105   아시아경제   
...                                                  ...       ...     ...   
13246  http://www.bigkinds.or.kr/news/newsDetailView....  20180731     SBS   
13247  http://www.bigkinds.or.kr/news/newsDetailView....  20180731    한국일보   
13248  http://www.bigkinds.or.kr/news/newsDetailView....  20180731    한국일보   
13249  http://www.bigkinds.or.kr/news/newsDetailView....  20180731    한국일보   
13250  http://www.bigkinds.or.kr/news/newsDetailView....  20180731    한국일보   
13251  http://www.bigkinds.or.kr/news/newsDetailView....  20180731    한국일보   
13252  http://www.bigkinds.or.kr/news/newsDetailView....  20180731    한국일보   
13253  http://www.bigkinds.or.kr/news/newsDetailView....  20180731    매일신문   
13254  http://www.bigkinds.or.kr/news/newsDetailView....  20180731    국민일보   
13255  http://www.bigkinds.or.kr/news/newsDetailView....  20180731   머니투데이   
13256  http://www.bigkinds.or.kr/news/newsDetailView....  20180731   머니투데이   
13257  http://www.bigkinds.or.kr/news/newsDetailView....  20180731     MBC   
13258  http://www.bigkinds.or.kr/news/newsDetailView....  20180731     MBC   
13259  http://www.bigkinds.or.kr/news/newsDetailView....  20180731    서울경제   
13260  http://www.bigkinds.or.kr/news/newsDetailView....  20180731   아시아경제   
13261  http://www.bigkinds.or.kr/news/newsDetailView....  20180731   아시아경제   
13262  http://www.bigkinds.or.kr/news/newsDetailView....  20180731   아시아경제   
13263  http://www.bigkinds.or.kr/news/newsDetailView....  20180731   아시아경제   
13264  http://www.bigkinds.or.kr/news/newsDetailView....  20180731   아시아경제   
13265  http://www.bigkinds.or.kr/news/newsDetailView....  20180731   아시아경제  

In [9]:
from sklearn.metrics.pairwise import euclidean_distances

### 유클리드 거리
* 유클리드 노름을 이용

In [10]:
euclidean_distances(tdm[0],tdm[1]) # 낮을 수록 유사하다

array([[4.69041576]])

In [11]:
article['본문'][0]

'존경하는 350만 도민 여러분! 2018년 무술년의 희망찬 새해가 밝았습니다. 새해 복 많이 받으십시오. 지난 한 해 우리 경남은 어려운 여건 속에도 도민 여러분과 소통하고 협치하며 경.. 지진, 폭염 등 새로운 유형의 재난에도 안전하고 쾌적한 환경에서 살아갈 수 있는 경남을 만들고 가야사 복원과 남명사상 재조명 등을 통해 긍지와 자부심을 더 높여나가겠습니다.'

In [12]:
import numpy as np

In [16]:
dist = euclidean_distances(tdm[1],tdm[2:])
np.argmin(dist)+1

4156

In [14]:
dis

array([[5.19615242, 3.31662479, 4.58257569, ..., 3.74165739, 4.35889894,
        6.55743852]])

In [17]:
article['본문'][1]

'‘추위를 잠시 피해가세요.’   31일 서울 은평구 디지털미디어시티역 버스 정류장에 설치된 노란색 텐트 안으로 사람들이 삼삼오오 모여들었다. 텐트에는 추위를 피해가라는 문구와 함께 ‘따스안’이라는 글씨가 적혀 있었다. .. 120여곳에 설치돼 폭염 속 보행자들에게 작은 그늘을 선사했던 서리풀원두막은 겨울이 되면서 주민 아이디어를 통해 서리풀트리로 거듭났다.'

In [18]:
article['본문'][4156]

'주거환경 개선 위한 노력                     한국토지주택공사(LH)가 천안청수 국민임대단지..LH는 미세먼지, 폭염, 층간소음 등으로 마음껏 뛰어놀 수 있는 공간이 부족한 어린이들에게 1년 내내 이용가능한 전천후 놀이시설을 제공하고 주거환경을 개선하기 위해 임대단지 내 실내놀이터 조성 사업을 추진하게 됐다.'

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

In [23]:
dist = cosine_similarity(tdm[1],tdm[2:]) # 클수록 유사하다.
np.argmax(dist)+1

12181

In [25]:
 article['본문'][12181]

'오늘 오전 8시쯤 서울 금천구청역 인근 고속선 열차 선로가 벌어져 서울에서 부산으로 가는 KTX 열차 4대가 지연됐습니다.  선로는 1시간 반 만에 복구됐지만 이 구간을 지나려던 열차들이 다른 길로 돌아가면서 최장 28분가량 운행이 늦어졌습니다.  코레일은 폭염의 영향으로 용접해놓은 선로 일부가 벌어진 것으로 보인다"며 "자세한 원인은 조사중"이라고 .."'

# 클러스터링 - 유사문서 군집화

In [26]:
from sklearn.cluster import SpectralClustering

In [27]:
cl = SpectralClustering(n_clusters=4, random_state=1234)

In [32]:
labels = cl.fit_predict(tdm[:500])
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 3, 3, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1, 0, 0, 0, 3, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,

In [30]:
from operator import itemgetter

In [36]:
freq_words = []
#  각 단어의 이름을 가져온다.
words = vectorizer.get_feature_names()
for i in range(4):
    count = tdm[labels == i, :].sum(axis=0)
    ws = [w for w,n in sorted(zip(words, count.flat), key=itemgetter(1),reverse=True)[:10]]
    freq_words.append(ws)
pd.DataFrame(freq_words)

0     1   2     3   4    5    6   7   8   9
0    폭염  미세먼지  재난    한파  지역  지난해   경기  안전  기후  사업
1    폭염   경로당  기온  미세먼지  안전   호주   도시  효과  관리  기관
2  미세먼지    기후  저감    폭염  기자   변화  에너지  여름  연구  지역
3    폭염  미세먼지  경기    안전  예정   위원   시간  지역  강풍  기록

In [54]:
cl = SpectralClustering(n_clusters=6,affinity=cosine_similarity, random_state=1234)

In [55]:
with open('data/trip.pkl','rb') as f:
    data =joblib.load(f)
locals().update(data)

In [58]:
labels = cl.fit_predict(tdm)
labels

C:\Users\p\Anaconda3\lib\site-packages\sklearn\manifold\spectral_embedding_.py:234: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn("Graph is not fully connected, spectral embedding"


array([5, 5, 0, 5, 5, 5, 5, 2, 0, 5, 0, 0, 0, 0, 5, 1, 1, 0, 1, 1, 4, 2,
       5, 0, 0, 5, 2, 0, 2, 0, 0, 0, 0, 5, 0, 1, 2, 5, 0, 5, 1, 0, 0, 0,
       5, 5, 2, 1, 0, 0, 1, 5, 5, 5, 0, 2, 0, 2, 0, 0, 2, 2, 5, 2, 1, 2,
       0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       4, 3, 0, 5, 0, 4, 4, 4, 0, 5, 1, 5, 2, 4, 0, 2, 0, 5, 0, 2, 1, 1,
       2, 0, 5, 2, 4, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 5, 5, 2, 2, 5, 1, 2,
       0, 1, 1, 5, 2, 1, 0, 5, 0, 2, 2, 0, 0, 1, 0, 2, 0, 2, 5, 5, 2, 0,
       0, 5, 2, 0, 0, 2, 0, 1, 0, 0, 0, 1, 0, 4, 0, 0, 5, 5, 5, 5, 5, 1,
       5, 0, 5, 3, 2, 1, 2, 1, 2, 1, 5, 2, 5, 0, 0, 0, 3, 3, 3, 0, 0, 0,
       3, 0, 5, 2, 2, 2, 2, 1, 5, 5, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       5, 0, 5, 0, 5, 0, 5, 5, 5, 5, 1, 5, 0, 1, 0, 0, 5, 1, 0, 3, 2, 0,
       4, 5, 5, 0, 5, 5, 0, 0, 3, 1, 0, 4, 2, 0, 4, 1, 4, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 5, 2, 0, 4, 5, 0, 1, 0, 0, 1, 0, 0, 0, 5, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 2, 1, 0, 2, 5, 0, 2, 2,

In [57]:
freq_words = []
#  각 단어의 이름을 가져온다.
words = vectorizer.get_feature_names()
for i in range(6):
    count = tdm[labels == i, :].sum(axis=0)
    ws = [w for w,n in sorted(zip(words, count.flat), key=itemgetter(1),reverse=True)[:10]]
    freq_words.append(ws)
pd.DataFrame(freq_words)

0    1    2    3    4    5    6    7     8    9
0  메뉴   생각  외국인  북어국   사람   방문  분위기   요리    타코   갈비
1  음식  분위기   사람   식사   추천   가정   느낌  북유럽    뷔페  스웨덴
2  직원   친절  칵테일   방문  분위기  동대문  테라스   사장  샌드위치   야경
3  버거   근처   수제   패티   !!   새벽   완전   주차    추천   치즈
4  치킨   양이   교촌   간장  브랜드   혼자  베이스   예전    지만  !!!
5  가격   식사   정도   !!   생각   시간   갈비   냄새  레스토랑   방문