### 다양한 방법으로 ndarray 생성하기

In [2]:
import numpy as np

#### np.array 함수로 생성하기

In [3]:
x = np.array([1,2,3,4])
print(x)

y = np.array([[4,5,6],[7,8,9]])
print(y)

[1 2 3 4]
[[4 5 6]
 [7 8 9]]


#### np.arange 함수로 생성하기

In [4]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [6]:
np.arange(2,5)

array([2, 3, 4])

In [8]:
np.arange(1,10,3)

array([1, 4, 7])

#### np.ones, np.zeros로 생성하기

In [9]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

#### np.empty, np.full로 생성하기

In [12]:
np.empty((2,2))

array([[1., 1.],
       [1., 1.]])

In [13]:
np.full((2,2,2),7)

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

#### np.eye로 생성하기
 - 단위 행렬 생성

In [14]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

#### np.linspace로 생성하기

In [16]:
np.linspace(1,10,2)

array([ 1., 10.])

In [17]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### reshape 함수 활용
 - ndarray의 형태, 차원을 바꾸기 위해 사용

In [19]:
x = np.arange(4)
print(x)

[0 1 2 3]


In [20]:
x.shape

(4,)

In [21]:
x.reshape(2,2)

array([[0, 1],
       [2, 3]])