### ndarray 기본 함수 사용하기

In [1]:
import numpy as np

- numpy documentation
    - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
    - numpy 문서

In [3]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)

print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.02677584 0.00563769 0.68687174 0.99113138 0.6646855 ]
 [0.88152414 0.01030115 0.90574114 0.02495431 0.49538188]
 [0.69171215 0.76954895 0.37465222 0.18159439 0.1029163 ]]


- 연산 함수
    - add, substract, multiply, divide

In [4]:
np.add(x,y)

array([[ 0.02677584,  1.00563769,  2.68687174,  3.99113138,  4.6646855 ],
       [ 5.88152414,  6.01030115,  7.90574114,  8.02495431,  9.49538188],
       [10.69171215, 11.76954895, 12.37465222, 13.18159439, 14.1029163 ]])

In [5]:
np.divide(x,y)

array([[  0.        , 177.37763003,   2.91175178,   3.02684392,
          6.01788366],
       [  5.67199442, 582.459266  ,   7.72847744, 320.58588253,
         18.1678022 ],
       [ 14.45688073,  14.2940875 ,  32.02970485,  71.58811616,
        136.03287154]])

In [6]:
x + y

array([[ 0.02677584,  1.00563769,  2.68687174,  3.99113138,  4.6646855 ],
       [ 5.88152414,  6.01030115,  7.90574114,  8.02495431,  9.49538188],
       [10.69171215, 11.76954895, 12.37465222, 13.18159439, 14.1029163 ]])

In [7]:
x / y

array([[  0.        , 177.37763003,   2.91175178,   3.02684392,
          6.01788366],
       [  5.67199442, 582.459266  ,   7.72847744, 320.58588253,
         18.1678022 ],
       [ 14.45688073,  14.2940875 ,  32.02970485,  71.58811616,
        136.03287154]])

- 통계 함수
    - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [8]:
print(y)

[[0.02677584 0.00563769 0.68687174 0.99113138 0.6646855 ]
 [0.88152414 0.01030115 0.90574114 0.02495431 0.49538188]
 [0.69171215 0.76954895 0.37465222 0.18159439 0.1029163 ]]


In [9]:
np.mean(y)

0.4542285845765512

In [10]:
y.mean()

0.4542285845765512

In [11]:
np.max(y)

0.991131383243009

In [12]:
np.argmax(y)

3

In [13]:
np.var(y)

0.12666822344004044

In [14]:
np.median(y)

0.4953818794478547

In [15]:
np.std(y)

0.35590479547210435

- 집계함수
    - 합계, 누적합계 등등

In [16]:
y

array([[0.02677584, 0.00563769, 0.68687174, 0.99113138, 0.6646855 ],
       [0.88152414, 0.01030115, 0.90574114, 0.02495431, 0.49538188],
       [0.69171215, 0.76954895, 0.37465222, 0.18159439, 0.1029163 ]])

In [17]:
np.sum(y,axis=None)

6.813428768648268

In [18]:
np.cumsum(y)

array([0.02677584, 0.03241353, 0.71928526, 1.71041664, 2.37510214,
       3.25662628, 3.26692743, 4.17266858, 4.19762289, 4.69300477,
       5.38471691, 6.15426586, 6.52891808, 6.71051247, 6.81342877])

- any, all 함수
    - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
    - all : 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [19]:
z = np.random.randn(10)
print(z)

[-0.61968787 -0.04454351  0.39910322  0.79644902 -0.27091838  0.77646886
  0.24443243  0.48696496 -0.57827027 -0.28330784]


In [20]:
z>0

array([False, False,  True,  True, False,  True,  True,  True, False,
       False])

In [21]:
np.any(z>0)

True

In [22]:
np.all(z != 0 )

True

- where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [23]:
z = np.random.randn(10)
print(z)

[ 0.4552018  -0.3271634   0.26465921  0.47198639  0.71925069 -1.26061386
  0.446123    0.46651294  1.55442912 -1.12812338]


In [24]:
np.where(z > 0, z, 0)

array([0.4552018 , 0.        , 0.26465921, 0.47198639, 0.71925069,
       0.        , 0.446123  , 0.46651294, 1.55442912, 0.        ])