### broadcasting 이해 및 활용하기

In [1]:
import numpy as np

- 브로드캐스팅
    - Shape가 같은 두 ndarray에 대한 연산은 각 원소별로 진행
    - 연산되는 두 ndarray가 다른 shape를 갖는 경우 브로드 캐스팅(Shape를 맞춤) 후 진행

- 브로드 캐스팅 률
    - 뒷 차원에서 부터 비교하여 Shape가 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

- 쉐이프가 같은 경우 연산

In [6]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.49215847 0.45234206 0.37114907 0.81417435 0.3083786 ]
 [0.05714812 0.45191364 0.24756931 0.2497059  0.09705017]
 [0.75139647 0.03162144 0.64856183 0.80722979 0.73074764]]


In [7]:
x*y

array([[ 0.        ,  0.45234206,  0.74229815,  2.44252305,  1.2335144 ],
       [ 0.28574062,  2.71148185,  1.73298514,  1.99764721,  0.87345154],
       [ 7.5139647 ,  0.34783579,  7.78274201, 10.49398722, 10.23046693]])

In [8]:
x % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [9]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)
d = b.reshape(1, 3)

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(d)

(4, 3)
(3,)
(4,)
(1, 3)
[[100 101 102]]


In [10]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [11]:
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [12]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])