- linalg 서브모듈 함수 활용하여 선형대수 연산하기

In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [12]:
x = np.random.rand(3, 3, 3)
print(x)


[[[0.87556049 0.60858122 0.3870532 ]
  [0.09870571 0.22533121 0.86717106]
  [0.60541632 0.03537042 0.87721161]]

 [[0.91604975 0.90535427 0.05011153]
  [0.89122148 0.05077985 0.60180951]
  [0.11163293 0.649254   0.61860926]]

 [[0.05624497 0.24386294 0.43732052]
  [0.16266571 0.01118997 0.39018126]
  [0.92552967 0.7560655  0.61044177]]]


In [13]:
np.matmul(x, np.linalg.inv(x))
np.linalg.inv(x)
#x @ np.linalg.inv(x)

array([[[ 0.46184847, -1.4386234 ,  1.21837494],
        [ 1.21252506,  1.47612429, -1.99423258],
        [-0.36764006,  0.93336081,  0.3795125 ]],

       [[ 0.48637982,  0.71407591, -0.7340836 ],
        [ 0.65534269, -0.75950024,  0.68578708],
        [-0.77557822,  0.66826381,  1.02924081]],

       [[-2.97401201,  1.87600761,  0.93147863],
        [ 2.70212042, -3.82282442,  0.50766797],
        [ 1.16236526,  1.89044232, -0.40289075]]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$

In [9]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])

x = np.linalg.solve(A, B)
print(x)
# np.allclose(A@x, B)

[18.  7.]
