In [1]:
import cv2
import numpy as np

In [2]:
image_bgr = cv2.imread('../data/Lena.png', cv2.IMREAD_COLOR)
print(image_bgr.shape)

(512, 512, 3)


1. 이미지를 부동 소수점으로 변환
2. BGR -> RGB
3. 높이 너비 채널 -> 채널 너비 높이 로변환
4. 채널 너비 높이 텐서에 배치에 포함된 이미지수 추가

In [3]:
image_bgr_float = image_bgr.astype(np.float32)
image_rgb = image_bgr_float[..., ::-1]
tensor_chw = np.transpose(image_rgb, (2, 0, 1))
tensor_nchw = tensor_chw[np.newaxis, ...]

print(tensor_nchw.shape)

(1, 3, 512, 512)


In [8]:
image_bgr_float[0][0]

array([125., 137., 226.], dtype=float32)

In [10]:
image_rgb[0][0]

array([226., 137., 125.], dtype=float32)

In [15]:
tensor_chw.shape

(3, 512, 512)

In [20]:
tensor_nchw[0]

array([[[226., 226., 223., ..., 230., 221., 200.],
        [226., 226., 223., ..., 230., 221., 200.],
        [226., 226., 223., ..., 230., 221., 200.],
        ...,
        [ 84.,  84.,  92., ..., 173., 172., 177.],
        [ 82.,  82.,  96., ..., 179., 181., 185.],
        [ 82.,  82.,  96., ..., 179., 181., 185.]],

       [[137., 137., 137., ..., 148., 130.,  99.],
        [137., 137., 137., ..., 148., 130.,  99.],
        [137., 137., 137., ..., 148., 130.,  99.],
        ...,
        [ 18.,  18.,  27., ...,  73.,  68.,  62.],
        [ 22.,  22.,  32., ...,  70.,  71.,  74.],
        [ 22.,  22.,  32., ...,  70.,  71.,  74.]],

       [[125., 125., 133., ..., 122., 110.,  90.],
        [125., 125., 133., ..., 122., 110.,  90.],
        [125., 125., 133., ..., 122., 110.,  90.],
        ...,
        [ 60.,  60.,  58., ...,  84.,  76.,  79.],
        [ 57.,  57.,  62., ...,  79.,  81.,  81.],
        [ 57.,  57.,  62., ...,  79.,  81.,  81.]]], dtype=float32)

In [17]:
tensor_nchw[0][0]

array([[226., 226., 223., ..., 230., 221., 200.],
       [226., 226., 223., ..., 230., 221., 200.],
       [226., 226., 223., ..., 230., 221., 200.],
       ...,
       [ 84.,  84.,  92., ..., 173., 172., 177.],
       [ 82.,  82.,  96., ..., 179., 181., 185.],
       [ 82.,  82.,  96., ..., 179., 181., 185.]], dtype=float32)