In [4]:
import numpy as np

In [6]:
test_exmaple = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_exmaple

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
test_exmaple[0][0]

1

In [8]:
test_exmaple[0,0]

1

- Matrix 0,0 에 10 

In [9]:
test_exmaple[0,0] = 10 
test_exmaple

array([[10,  2,  3],
       [ 4,  5,  6]])

In [10]:
test_exmaple[0][0] = 5 # Matrix 0,0 에 12 할당
test_exmaple[0,0]

5

#### slicing

- 1,2행만 출력

In [11]:
test_exmaple = np.array([
    [1, 2, 5,1], [1, 2, 5,2],[1, 2, 5,3],[1, 2, 5,4]], int)
test_exmaple[:2,:] 

array([[1, 2, 5, 1],
       [1, 2, 5, 2]])

- 전체 행의 1,2열만 출력

In [15]:
test_exmaple[:,1:3] 

array([[2, 5],
       [2, 5],
       [2, 5],
       [2, 5]])

- 2행의 0,1열만 출력

In [14]:
test_exmaple[1,:2] 

array([1, 2])

- 전체행의 2열 이상 부터 출력

In [18]:
test_exmaple = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
test_exmaple[:,2:] 

array([[ 3,  4,  5],
       [ 8,  9, 10]])

- 1행의 1,2열

In [19]:
test_exmaple[1,1:3] 

array([7, 8])

- 1,2행

In [20]:
test_exmaple[1:3] # 1 Row ~ 2Row의 전체

array([[ 6,  7,  8,  9, 10]])

In [24]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

- 앞의 -1은 전체 행의 맨 마지막 열을 말하고 reshape의 -1,1은 1은 1열로 표현하고 -1은 자동으로 맞춰주는 것을 뜻한다

In [25]:
a[:, -1].reshape(-1,1)

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])