In [4]:
import numpy as np

#### arange

- list의 range 효과

In [5]:
np.arange(30) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
np.arange(0, 5, 0.5) # floating point도 표시가능함

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [7]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

#### ones, zeros & empty

- zeros - 0 으로 가득찬 nparayy생성

In [8]:
np.zeros(shape=(10,), dtype=np.int8) 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [9]:
np.zeros((2,5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

- 1로 가득찬 nparaay 생성

In [10]:
np.ones(shape=(10,), dtype=np.int8) 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [11]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

- shape 만 주어지고 비어있는 nparray생성 메모리 초기화 안됨

In [12]:
np.empty(shape=(10,), dtype=np.int8) 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [13]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

- array의 크기만큼 해당 숫자를 넣어 반환 여기서는 0

In [14]:
test_matrix = np.arange(30).reshape(5,6)
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

#### eye, identity & digonal

- identity : 단위 행렬을 생성

In [15]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [16]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

- 대각선이 1인행렬 생성, k 값의 시작 인덱스 변경 가능

In [17]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- k는 시작점

In [19]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

- diag 대각 행렬의 각을 추출함

In [25]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
np.diag(matrix)

array([0, 4, 8])

In [22]:
np.diag(matrix, k=1)

array([1, 5])

# random sampling

- 데이터 분포에 따른 샘플링으로 array 생성

- 균등분포

In [23]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.16001579, 0.08027195, 0.68039649, 0.053603  , 0.11399446],
       [0.13864012, 0.53378651, 0.83863185, 0.81889654, 0.88861694]])

In [24]:
np.random.normal(0,1,10).reshape(2,5)

array([[-0.65558701,  0.93354273,  0.97292404,  0.21946597, -1.13211925],
       [-1.26712866, -0.66214122,  0.95906993, -0.93299976, -1.35055738]])